name: appetito
description: "Ordering food easily."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: JosefinSans
      fonts:
        - asset: fonts/JosefinSans-BoldItalic.ttf
          weight: 700
          style: normal

    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
          style: normal
        - asset: fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
          style: normal
        - asset: fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Poppins-Light.ttf
          weight: 300
          style: normal
        - asset: fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
          style: normal
        - asset: fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
          style: normal
        - asset: fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
          style: normal
        - asset: fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
          style: normal
        - asset: fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Poppins-Black.ttf
          weight: 900
          style: normal
        - asset: fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
